#!/bin/bash
set -ex

# Build kokkos 
cd ~
mkdir .installations 
mkdir .work
cd .work

git clone https://github.com/kokkos/kokkos.git
mkdir kokkos/build
cd kokkos/build
cmake -DCMAKE_INSTALL_PREFIX=~/.installations/Kokkos \
          -DKokkos_ENABLE_SERIAL=ON \
          -DKokkos_ENABLE_OPENMP=ON \
          -DBUILD_SHARED_LIBS=ON    \
          -DKokkos_CXX_STANDARD=17  \
../
make install


# Install MParT
cd ~/.work
git clone -b main --single-branch https://github.com/MeasureTransport/MParT.git
mkdir MParT/build
cd MParT/build 
cmake -DMPART_BUILD_TESTS=OFF -DKokkos_DIR=~/.installations/Kokkos/lib/cmake/Kokkos -DCMAKE_INSTALL_PREFIX=~/.installations/MParT ../
make install 

# Clean up build folders
cd ~
rm -rf ~/.work
