#!/bin/bash
set -ex

# Build kokkos 
mkdir Installations 
git clone https://github.com/kokkos/kokkos.git
mkdir kokkos/build
cd kokkos/build
cmake -DCMAKE_INSTALL_PREFIX=~/Installations/Kokkos \
          -DKokkos_ENABLE_SERIAL=ON \
          -DKokkos_ENABLE_OPENMP=ON \
          -DBUILD_SHARED_LIBS=ON    \
          -DKokkos_CXX_STANDARD=17  \
../
make install


# Install MParT
cd ~
git clone -b tests-option --single-branch https://github.com/MeasureTransport/MParT.git
mkdir MParT/build
cd MParT/build 
cmake -DMPART_BUILD_TESTS=OFF -DKokkos_DIR=~/Installations/Kokkos/lib/cmake/Kokkos -DCMAKE_INSTALL_PREFIX=~/Installations/MParT ../
make install 
cd ../../

# Update paths 
export PYTHONPATH=$PYTHONPATH:${PWD}/Installations/MParT/python
